name: holion_common_exmple
description: Demonstrates how to use the holion_common's miscellaneous functionality 
version: 0.0.1
homepage: https://holion.dk/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  holion_common:
    path: ../
  humio: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
